<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\User' . "\0" . 'id', '' . "\0" . 'App\\Entity\\User' . "\0" . 'email', '' . "\0" . 'App\\Entity\\User' . "\0" . 'password', '' . "\0" . 'App\\Entity\\User' . "\0" . 'account_name', '' . "\0" . 'App\\Entity\\User' . "\0" . 'img_path', '' . "\0" . 'App\\Entity\\User' . "\0" . 'available_time', '' . "\0" . 'App\\Entity\\User' . "\0" . 'score', '' . "\0" . 'App\\Entity\\User' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\User' . "\0" . 'updated_at', '' . "\0" . 'App\\Entity\\User' . "\0" . 'program_bookmarks', '' . "\0" . 'App\\Entity\\User' . "\0" . 'exercise_bookmarks', '' . "\0" . 'App\\Entity\\User' . "\0" . 'followed_programs', '' . "\0" . 'App\\Entity\\User' . "\0" . 'exercise_comments', '' . "\0" . 'App\\Entity\\User' . "\0" . 'program_comments', '' . "\0" . 'App\\Entity\\User' . "\0" . 'access_level', '' . "\0" . 'App\\Entity\\User' . "\0" . 'mastery_level'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\User' . "\0" . 'id', '' . "\0" . 'App\\Entity\\User' . "\0" . 'email', '' . "\0" . 'App\\Entity\\User' . "\0" . 'password', '' . "\0" . 'App\\Entity\\User' . "\0" . 'account_name', '' . "\0" . 'App\\Entity\\User' . "\0" . 'img_path', '' . "\0" . 'App\\Entity\\User' . "\0" . 'available_time', '' . "\0" . 'App\\Entity\\User' . "\0" . 'score', '' . "\0" . 'App\\Entity\\User' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\User' . "\0" . 'updated_at', '' . "\0" . 'App\\Entity\\User' . "\0" . 'program_bookmarks', '' . "\0" . 'App\\Entity\\User' . "\0" . 'exercise_bookmarks', '' . "\0" . 'App\\Entity\\User' . "\0" . 'followed_programs', '' . "\0" . 'App\\Entity\\User' . "\0" . 'exercise_comments', '' . "\0" . 'App\\Entity\\User' . "\0" . 'program_comments', '' . "\0" . 'App\\Entity\\User' . "\0" . 'access_level', '' . "\0" . 'App\\Entity\\User' . "\0" . 'mastery_level'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccountName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccountName', []);

        return parent::getAccountName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccountName(string $account_name): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccountName', [$account_name]);

        return parent::setAccountName($account_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getImgPath(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgPath', []);

        return parent::getImgPath();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgPath(?string $img_path): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgPath', [$img_path]);

        return parent::setImgPath($img_path);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailableTime(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailableTime', []);

        return parent::getAvailableTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailableTime(?int $available_time): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvailableTime', [$available_time]);

        return parent::setAvailableTime($available_time);
    }

    /**
     * {@inheritDoc}
     */
    public function getScore(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScore', []);

        return parent::getScore();
    }

    /**
     * {@inheritDoc}
     */
    public function setScore(int $score): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScore', [$score]);

        return parent::setScore($score);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $created_at): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$created_at]);

        return parent::setCreatedAt($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(?\DateTimeInterface $updated_at): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updated_at]);

        return parent::setUpdatedAt($updated_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getProgramBookmarks(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgramBookmarks', []);

        return parent::getProgramBookmarks();
    }

    /**
     * {@inheritDoc}
     */
    public function addProgramBookmark(\App\Entity\Program $programBookmark): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProgramBookmark', [$programBookmark]);

        return parent::addProgramBookmark($programBookmark);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProgramBookmark(\App\Entity\Program $programBookmark): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProgramBookmark', [$programBookmark]);

        return parent::removeProgramBookmark($programBookmark);
    }

    /**
     * {@inheritDoc}
     */
    public function getExerciseBookmarks(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExerciseBookmarks', []);

        return parent::getExerciseBookmarks();
    }

    /**
     * {@inheritDoc}
     */
    public function addExerciseBookmark(\App\Entity\exercise $exerciseBookmark): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExerciseBookmark', [$exerciseBookmark]);

        return parent::addExerciseBookmark($exerciseBookmark);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExerciseBookmark(\App\Entity\exercise $exerciseBookmark): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExerciseBookmark', [$exerciseBookmark]);

        return parent::removeExerciseBookmark($exerciseBookmark);
    }

    /**
     * {@inheritDoc}
     */
    public function getFollowedPrograms(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFollowedPrograms', []);

        return parent::getFollowedPrograms();
    }

    /**
     * {@inheritDoc}
     */
    public function addFollowedProgram(\App\Entity\Program $followedProgram): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFollowedProgram', [$followedProgram]);

        return parent::addFollowedProgram($followedProgram);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFollowedProgram(\App\Entity\Program $followedProgram): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFollowedProgram', [$followedProgram]);

        return parent::removeFollowedProgram($followedProgram);
    }

    /**
     * {@inheritDoc}
     */
    public function getExerciseComments(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExerciseComments', []);

        return parent::getExerciseComments();
    }

    /**
     * {@inheritDoc}
     */
    public function addExerciseComment(\App\Entity\ExerciseComment $exerciseComment): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExerciseComment', [$exerciseComment]);

        return parent::addExerciseComment($exerciseComment);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExerciseComment(\App\Entity\ExerciseComment $exerciseComment): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExerciseComment', [$exerciseComment]);

        return parent::removeExerciseComment($exerciseComment);
    }

    /**
     * {@inheritDoc}
     */
    public function getProgramComments(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgramComments', []);

        return parent::getProgramComments();
    }

    /**
     * {@inheritDoc}
     */
    public function addProgramComment(\App\Entity\ProgramComment $programComment): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProgramComment', [$programComment]);

        return parent::addProgramComment($programComment);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProgramComment(\App\Entity\ProgramComment $programComment): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProgramComment', [$programComment]);

        return parent::removeProgramComment($programComment);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccessLevel(): ?\App\Entity\AccessLevel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccessLevel', []);

        return parent::getAccessLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccessLevel(?\App\Entity\AccessLevel $access_level): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccessLevel', [$access_level]);

        return parent::setAccessLevel($access_level);
    }

    /**
     * {@inheritDoc}
     */
    public function getMasteryLevel(): ?\App\Entity\MasteryLevel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMasteryLevel', []);

        return parent::getMasteryLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setMasteryLevel(?\App\Entity\MasteryLevel $mastery_level): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMasteryLevel', [$mastery_level]);

        return parent::setMasteryLevel($mastery_level);
    }

}
