<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUdCYBhx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUdCYBhx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUdCYBhx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUdCYBhx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUdCYBhx\App_KernelDevDebugContainer([
    'container.build_hash' => 'UdCYBhx',
    'container.build_id' => '2709455a',
    'container.build_time' => 1583359926,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUdCYBhx');
