<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC260C27\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC260C27/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC260C27.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC260C27\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC260C27\App_KernelDevDebugContainer([
    'container.build_hash' => 'C260C27',
    'container.build_id' => '8e382699',
    'container.build_time' => 1584980945,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC260C27');
